
bash imagenet_search_caspr_adaptive_30_hparams.sh 0
bash imagenet_search_caspr_adaptive_30_hparams.sh 1
bash imagenet_search_caspr_adaptive_30_hparams.sh 2
bash imagenet_search_caspr_adaptive_30_hparams.sh 3
